/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Button({ children }) {
  return (
    <button className="gap-2 self-stretch px-4 py-2 w-full font-medium rounded-md shadow-sm bg-zinc-900 min-h-[36px] text-neutral-50">
      {children}
    </button>
  );
}

export default Button;
