/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TermsAndPolicy() {
  return (
    <div className="mt-6 leading-5">
      <span className="text-zinc-500">
        By clicking continue, you agree to our{" "}
      </span>
      <br />
      <a
        href="https://ui.shadcn.com/terms"
        className="underline text-zinc-500"
        target="_blank"
        rel="noopener noreferrer"
      >
        Terms of Service
      </a>
      <span className="text-zinc-500"> and </span>
      <a
        href="https://ui.shadcn.com/privacy"
        className="underline text-zinc-500"
        target="_blank"
        rel="noopener noreferrer"
      >
        Privacy Policy
      </a>
      <span className="text-zinc-500">.</span>
    </div>
  );
}

export default TermsAndPolicy;
