/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Divider() {
  return (
    <div className="flex justify-center items-start mt-6 w-full">
      <div className="flex flex-col flex-1 shrink justify-center py-4 basis-5">
        <div className="flex w-full border border-solid border-zinc-200 min-h-[1px]" />
      </div>
      <div className="flex flex-col justify-center items-center p-2.5 text-xs leading-none text-center bg-white text-zinc-500">
        <div className="gap-2.5">OR CONTINUE WITH</div>
      </div>
      <div className="flex flex-col flex-1 shrink justify-center py-4 basis-5">
        <div className="flex w-full border border-solid border-zinc-200 min-h-[1px]" />
      </div>
    </div>
  );
}

export default Divider;
