/**
 * This code was generated by Builder.io.
 */
import React from "react";

function EmailInput() {
  return (
    <div className="flex flex-col w-full text-sm leading-none">
      <label htmlFor="email" className="sr-only">
        Email
      </label>
      <input
        type="email"
        id="email"
        placeholder="name@example.com"
        className="overflow-hidden self-stretch px-3 py-2 w-full whitespace-nowrap bg-white rounded-md border border-solid shadow-sm border-zinc-200 min-h-[36px] text-zinc-500"
        aria-label="Email"
      />
    </div>
  );
}

export default EmailInput;
