/**
 * This code was generated by Builder.io.
 */
import React from "react";
import EmailInput from "./EmailInput";
import SubmitButton from "./SubmitButton";
import Divider from "./Divider";
import TermsAndPolicy from "./TermsAndPolicy";

function SignUp() {
  return (
    <main className="flex overflow-hidden bg-white">
      <section className="flex flex-col flex-1 shrink justify-center items-center w-full basis-0 min-w-[240px] max-md:max-w-full">
        <header className="flex flex-col justify-center items-center py-2">
          <h1 className="text-2xl font-semibold tracking-tight leading-none text-zinc-950">
            Create an account
          </h1>
          <p className="text-sm leading-none text-zinc-500">
            Enter your email below to create your account
          </p>
        </header>
        <form className="flex flex-col mt-6 max-w-full w-[350px]">
          <EmailInput />
          <SubmitButton />
          <Divider />
          <TermsAndPolicy />
        </form>
      </section>
    </main>
  );
}

export default SignUp;
