/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TermsAndPolicy() {
  return (
    <p className="mt-6 text-sm leading-5 text-zinc-500">
      By clicking continue, you agree to our{" "}
      <a
        href="https://ui.shadcn.com/terms"
        className="underline text-zinc-500"
        target="_blank"
        rel="noopener noreferrer"
      >
        Terms of Service
      </a>{" "}
      and{" "}
      <a
        href="https://ui.shadcn.com/privacy"
        className="underline text-zinc-500"
        target="_blank"
        rel="noopener noreferrer"
      >
        Privacy Policy
      </a>
      .
    </p>
  );
}

export default TermsAndPolicy;
