/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../components/Header";
import PropertyListing from "../components/PropertyListing";
import Footer from "../components/Footer";

function BiddingPage() {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <main>
        <PropertyListing />
      </main>
      <Footer />
    </div>
  );
}

export default BiddingPage;
