/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../components/Header";
import ProductSection from "../components/ProductSection";
import Footer from "../components/Footer";

const biddingProducts = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c2ca999b195c0b55da726b8147d70ad9618eb8712bbf9290d0b6c3f4ac5f5eb1?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c2ca999b195c0b55da726b8147d70ad9618eb8712bbf9290d0b6c3f4ac5f5eb1?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c2ca999b195c0b55da726b8147d70ad9618eb8712bbf9290d0b6c3f4ac5f5eb1?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
  },
];

const directBuyProducts = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c2ca999b195c0b55da726b8147d70ad9618eb8712bbf9290d0b6c3f4ac5f5eb1?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c2ca999b195c0b55da726b8147d70ad9618eb8712bbf9290d0b6c3f4ac5f5eb1?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
  },
];

function Listing() {
  return (
    <main className="flex overflow-hidden flex-col bg-white">
      <Header />
      <ProductSection title="Bidding" products={biddingProducts} />
      <ProductSection title="Direct Buy" products={directBuyProducts} />
      <Footer />
    </main>
  );
}

export default Listing;
