/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AuthButtons() {
  return (
    <div className="flex gap-4 justify-center items-center self-stretch my-auto rounded">
      <button className="gap-2 self-stretch px-5 py-2 my-auto text-blue-600 rounded border border-blue-600 border-solid">
        Log In
      </button>
      <button className="gap-2 self-stretch px-5 py-2 my-auto text-white bg-blue-600 rounded">
        Sign Up
      </button>
    </div>
  );
}

export default AuthButtons;
