/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Button({ children, variant = "solid" }) {
  const baseClasses = "gap-2 self-stretch px-5 py-2 my-auto rounded";
  const variantClasses = {
    outline: "text-blue-600 border border-blue-600 border-solid",
    solid: "text-white bg-blue-600",
  };

  return (
    <button className={`${baseClasses} ${variantClasses[variant]}`}>
      {children}
    </button>
  );
}

export default Button;
