/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Link } from "react-router-dom";

const FeatureSection = ({ title, description, features, imageUrl }) => {
  return (
    <section className="flex overflow-hidden flex-col justify-center px-16 py-28 w-full bg-white max-md:px-5 max-md:py-24 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 items-center w-full max-md:max-w-full">
        <div className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 min-w-[240px] max-md:max-w-full">
          <div className="flex flex-col w-full text-black max-md:max-w-full">
            <div className="flex flex-col w-full max-md:max-w-full">
              <div className="flex flex-col w-full max-md:max-w-full">
                <h2 className="text-5xl font-bold leading-[58px] max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
                  {title}
                </h2>
                <p className="mt-6 text-lg leading-7 max-md:max-w-full">
                  {description}
                </p>
              </div>
            </div>
            <div className="flex flex-wrap gap-6 items-start py-2 mt-8 w-full max-md:max-w-full">
              {features.map((feature, index) => (
                <div
                  key={index}
                  className="flex flex-col flex-1 shrink basis-0 min-w-[240px]"
                >
                  <h3 className="text-xl font-bold leading-snug">
                    {feature.title}
                  </h3>
                  <p className="mt-4 text-base leading-6">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
          <div className="flex gap-6 items-center self-start pt-4 mt-6 text-base text-blue-600">
            <Link
              to="/learn-more"
              className="gap-2 self-stretch px-6 py-3 my-auto border border-blue-600 border-solid max-md:px-5"
            >
              Learn More
            </Link>
          </div>
        </div>
        <img
          loading="lazy"
          src={imageUrl}
          alt="Feature illustration"
          className="object-contain flex-1 shrink self-stretch my-auto w-full aspect-[0.96] basis-0 min-w-[240px] max-md:max-w-full"
        />
      </div>
    </section>
  );
};

export default FeatureSection;
