/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FooterColumn({ title, items }) {
  return (
    <div className="flex overflow-hidden flex-col flex-1 shrink basis-0">
      <h3 className="text-base font-semibold text-black">{title}</h3>
      <ul className="flex flex-col mt-4 w-full text-sm text-black whitespace-nowrap">
        {items.map((item, index) => (
          <li key={index} className="flex-1 shrink py-2 w-full">
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default FooterColumn;
