/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FooterLinks() {
  const linkSections = [
    {
      title: "About Us",
      links: ["Contact", "FAQ", "Support", "Terms", "Privacy"],
    },
    {
      title: "Resources",
      links: ["Blog", "Guides", "Tutorials", "Help Center", "Community"],
    },
    {
      title: "Partners",
      links: ["Affiliates", "Investors", "Careers", "Press", "Events"],
    },
  ];

  return (
    <>
      {linkSections.map((section, index) => (
        <div
          key={index}
          className="flex overflow-hidden flex-col flex-1 shrink basis-0"
        >
          <h3 className="text-base font-semibold text-black">
            {section.title}
          </h3>
          <ul className="flex flex-col mt-4 w-full text-sm text-black whitespace-nowrap">
            {section.links.map((link, linkIndex) => (
              <li key={linkIndex} className="flex-1 shrink py-2 w-full">
                <a href="#">{link}</a>
              </li>
            ))}
          </ul>
        </div>
      ))}
    </>
  );
}

export default FooterLinks;
