/**
 * This code was generated by Builder.io.
 */
import React, { act } from "react";
import { Link } from "react-router-dom";

const StepCard = ({ imageUrl, title, description, actionText, actionUrl, actionIcon }) => (
  <div className="flex overflow-hidden flex-col flex-1 shrink basis-0 min-w-[240px]">
    <img
      loading="lazy"
      src={imageUrl}
      alt={title}
      className="object-contain w-full aspect-[1.69]"
    />
    <div className="flex flex-col mt-8 w-full">
      <div className="flex flex-col items-start w-full text-center text-black">
        <h3 className="text-2xl font-bold leading-9">{title}</h3>
        <p className="mt-4 text-base leading-6">{description}</p>
      </div>
      <div className="flex flex-col items-center pt-2 mt-6 w-full text-base text-blue-600">
        <Link to={actionUrl} className="flex gap-2 justify-center items-center">
          <span className="self-stretch my-auto">{actionText}</span>
          <img
            loading="lazy"
            src={actionIcon}
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
          />
        </Link>
      </div>
    </div>
  </div>
);

const HowItWorks = () => {
  const steps = [
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/8996904145a4662a5785aff6b678a7c1fb74cfdae8eef4619413452e72c65542?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
      title: "Easy Steps to Bid for Loans and Buy Properties",
      description: "1. Browse through our selection of loan mortgage vehicles.",
      actionText: "Get Started",
      actionUrl: "/listing",
      actionIcon:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/8c4f456122500a1c891a4b47215482f2db920b8371ba0dca09cecc57c600aded?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
    },
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/6dd824f9711d1cc25227494953668b166547215e932bef29cd8fa5dfef890f8a?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
      title: "Find Your Perfect Loan and Property Match",
      description: "2. Place a bid on the loan and vehicle of your choice.",
      actionText: "Bid",
      actionUrl: "/bidding",
      actionIcon:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/248d341ba34f7ee5617023475cac4008986aea18ed4c2e5bbbaeae2c173d0492?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
    },
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/d133ab38af167b99a415f9d0a5ef6353d1b95666c3009d294ac8ecd9b99f9c5d?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
      title: "Win the Auction and Secure Your Loan and Property",
      description:
        "3. If your bid is successful, complete the purchase process.",
      actionText: "Purchase",
      actionUrl: "/listing",
      actionIcon:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/88816643c2e407691698441ef13485bef8711c41bf8c7ad875ecc06442797c3b?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc",
    },
  ];

  return (
    <section className="flex overflow-hidden flex-col px-16 py-36 mt-12 w-full bg-white min-h-[914px] max-md:px-5 max-md:py-24 max-md:mt-10 max-md:max-w-full">
      <h2 className="self-center text-4xl font-bold leading-10 text-center text-black w-[768px] max-md:max-w-full">
        Discover How to Bid for Loans and Purchase Properties
      </h2>
      <div className="flex flex-wrap gap-10 justify-center items-start mt-20 w-full max-md:mt-10 max-md:max-w-full">
        {steps.map((step, index) => (
          <StepCard key={index} {...step} />
        ))}
      </div>
    </section>
  );
};

export default HowItWorks;
