/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/4d2bafb4e8503baed016efe47cc7dfafe9ba63cde48ce63f6acd76df0d39478e?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc"
      alt="Company Logo"
      className="object-contain shrink-0 self-stretch my-auto aspect-[2.33] w-[63px]"
    />
  );
}

export default Logo;
