/**
 * This code was generated by Builder.io.
 */
import React from "react";

function NavItem({ label, href, hasDropdown }) {
  return (
    <a href={href} className="flex gap-1 justify-center items-center">
      <span className="self-stretch my-auto">{label}</span>
      {hasDropdown && (
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fee1f4da4fbc0ac2471ce1f6c2ea6132c2a43490c7dcf7518142e53de96c1a55?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
        />
      )}
    </a>
  );
}

export default NavItem;
