/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Navigation() {
  const navItems = [
    { label: "Services", link: "#" },
    { label: "Legallities", link: "#" },
    { label: "About", link: "#" },
    { label: "More", link: "#", hasDropdown: true },
  ];

  return (
    <nav className="flex overflow-hidden gap-8 items-start self-stretch my-auto min-w-[240px]">
      {navItems.map((item, index) => (
        <a key={index} href={item.link} className="gap-2.5 self-stretch">
          {item.label}
          {item.hasDropdown && (
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/fee1f4da4fbc0ac2471ce1f6c2ea6132c2a43490c7dcf7518142e53de96c1a55?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
          )}
        </a>
      ))}
    </nav>
  );
}

export default Navigation;
