/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ProductCard({ imageSrc }) {
  return (
    <img
      loading="lazy"
      src={imageSrc}
      alt="Product"
      className="object-contain shrink-0 max-w-full aspect-[0.86] w-[342px]"
    />
  );
}

export default ProductCard;
