/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "./ProductCard";

function ProductSection({ title, products }) {
  return (
    <section className="flex flex-col pl-16 mt-11 w-full max-md:pl-5 max-md:mt-10 max-md:max-w-full">
      <h2 className="self-start text-6xl text-black max-md:text-4xl">
        {title}
      </h2>
      <div className="flex flex-wrap gap-5 justify-between items-start text-2xl text-stone-500 max-md:max-w-full">
        {products.map((product, index) => (
          <ProductCard key={index} {...product} />
        ))}
        <div className="flex flex-col self-stretch">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/127a11030f077182a65d3cba24f3a5fd29872a67977d18903d72203804577054?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc"
            alt=""
            className="object-contain aspect-[0.39] w-[155px]"
          />
          <div className="self-start mt-5 ml-4 max-md:ml-2.5">see more</div>
        </div>
      </div>
    </section>
  );
}

export default ProductSection;
