/**
 * This code was generated by Builder.io.
 */
import React from "react";

function PropertyCard({ name, type, price, description }) {
  return (
    <article className="flex flex-col w-full font-medium max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 max-md:mr-1 max-md:max-w-full">
        <div className="flex flex-col">
          <h2 className="text-4xl text-black">{name}</h2>
          <p className="self-start text-2xl text-stone-500">{type}</p>
        </div>
        <p className="grow shrink self-start text-2xl leading-9 text-black w-[408px] max-md:max-w-full">
          Starting from just <span className="text-4xl">₹ {price}</span> only
        </p>
      </div>
      <p className="mt-4 mr-6 text-xl leading-8 text-black max-md:mr-2.5 max-md:max-w-full">
        {description}
      </p>
    </article>
  );
}

export default PropertyCard;
