/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PropertyCard from "./PropertyCard";

function PropertyListing() {
  const properties = [
    {
      name: "Property Name",
      type: "Property Type",
      price: "XX,XX,XXX",
      description:
        "Lorem ipsum dolor sit amet consectetur. Orci sapien platea nulla adipiscing nunc quam dolor. Tincidunt fusce pharetra id lorem vitae id magna. Ullamcorper facilisi sed accumsan orci amet augue morbi imperdiet at. Aliquam viverra arcu morbi curabitur id cras orci. Condimentum suspendisse ultrices blandit eu at habitant. Tempus hac congue a enim leo lorem. Arcu maecenas fames cursus morbi curabitur. Egestas id imperdiet egestas",
    },
    // Repeat the object above 5 more times for a total of 6 properties
  ];

  return (
    <section className="flex flex-col px-16 mt-7 w-full max-md:px-5 max-md:max-w-full">
      <h1 className="self-start text-6xl text-black max-md:text-4xl">
        Bidding
      </h1>
      <div className="mt-10 max-md:mr-0.5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[31%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-10">
              {[1, 2, 3, 4, 5].map((_, index) => (
                <img
                  key={index}
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/b931082941425f5c54471824185c6efc8a7cda0d586834439ae8a8428002e5bd?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc"
                  alt={`Property ${index + 1}`}
                  className="object-contain w-full aspect-[1.5] max-md:mr-1 mt-16 first:mt-0"
                />
              ))}
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[69%] max-md:ml-0 max-md:w-full">
            {properties.map((property, index) => (
              <PropertyCard key={index} {...property} />
            ))}
          </div>
        </div>
      </div>
      <button className="self-end mt-24 mr-5 text-xl font-medium text-black max-md:mt-10 max-md:mr-2.5">
        See more
      </button>
    </section>
  );
}

export default PropertyListing;
