/**
 * This code was generated by Builder.io.
 */
import React from "react";

function PropertyDetails() {
  return (
    <section className="mt-16 max-md:mt-10">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c9e3d280d562e6bee20695261157815864881196741bce89bb53d6d50efc8d68?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc"
        alt="Property image"
        className="object-contain w-full aspect-[1.78] max-w-[1312px] max-md:max-w-full"
      />
      <div className="flex flex-wrap gap-5 justify-between mt-10 w-full max-w-[1281px] max-md:max-w-full">
        <div className="flex flex-col">
          <h1 className="text-8xl font-bold tracking-tighter text-black max-md:text-4xl">
            Mumbai
          </h1>
          <h2 className="z-10 self-start -mt-3.5 text-4xl tracking-tighter text-stone-500">
            Property type
          </h2>
        </div>
        <div className="flex flex-col my-auto font-medium text-black max-md:max-w-full">
          <p className="text-5xl tracking-tighter max-md:max-w-full max-md:text-4xl">
            Price starts from ₹ xxxx /-
          </p>
          <p className="self-end mt-4 text-2xl">Bidding ends in 00:00:00</p>
        </div>
      </div>
      <div className="flex flex-wrap gap-10 mt-5 w-full text-3xl text-white max-w-[1308px] max-md:max-w-full">
        <button className="flex-auto gap-2 self-stretch px-5 py-2 bg-black rounded-lg">
          Request Visit
        </button>
        <button className="flex-auto gap-2 self-stretch px-5 py-2 bg-black rounded-lg">
          Contact Saler
        </button>
      </div>
    </section>
  );
}

export default PropertyDetails;
