/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchArea = () => {
  return (
    <div className="flex flex-wrap gap-5 justify-center self-center mt-32 max-w-full text-3xl font-bold leading-tight text-center text-black w-full max-md:mt-10">
      <div className="flex gap-3.5 items-start p-2.5 rounded-xl border-2 border-black border-solid bg-stone-300">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b009277d7ee4a4842477fa99c2ef42a75e140d064719d1face9acae5dcdab931?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc"
          alt=""
          className="object-contain shrink-0 aspect-square w-[35px]"
        />
        <div>Search for an Area</div>
      </div>
      <div className="flex gap-10 items-center p-2.5 whitespace-nowrap rounded-xl border-2 border-black border-solid bg-stone-300 min-h-[56px]">
        <div className="self-stretch my-auto">Type</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/12aaa570e0758df038f8251c1dcccba54882d7aba5b2b181d973b7f0c64b28b3?placeholderIfAbsent=true&apiKey=525aac9cf92746e7a7350665a34e7ffc"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto aspect-[1.63] w-[13px]"
        />
      </div>
    </div>
  );
};

export default SearchArea;
