/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SubscribeForm() {
  return (
    <div className="flex flex-col min-w-[240px] w-[500px] max-md:max-w-full">
      <div className="flex flex-col w-full text-base text-black max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">Subscribe</h3>
        <p className="mt-4 max-md:max-w-full">
          Join our community to stay updated on the latest news and releases.
        </p>
      </div>
      <form className="flex flex-col mt-6 w-full max-md:max-w-full">
        <div className="flex flex-wrap gap-4 items-start w-full text-base max-md:max-w-full">
          <label htmlFor="email" className="sr-only">
            Enter email address
          </label>
          <input
            type="email"
            id="email"
            className="flex-1 shrink gap-2 self-stretch p-3 bg-white border border-black border-solid basis-6 min-w-[240px] text-stone-500"
            placeholder="Enter email address"
          />
          <button
            type="submit"
            className="gap-2 self-stretch px-6 py-3 text-black whitespace-nowrap border border-black border-solid w-[119px] max-md:px-5"
          >
            Subscribe
          </button>
        </div>
        <p className="mt-4 text-xs leading-5 text-black max-md:max-w-full">
          By subscribing, you agree to our Privacy Policy and consent to receive
          updates from our company.
        </p>
      </form>
    </div>
  );
}

export default SubscribeForm;
